version: "3.8"
services:
  ui:
    container_name: portfolio-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: portfolio-ui:latest
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app/ui
    env_file: .env.development

  api:
    container_name: portfolio-api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: portfolio-api:latest
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app/api
    env_file: .env.development
